# Generated by Django 6.0.5 on 2026-05-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название вакансии"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "short_description",
                    models.TextField(verbose_name="Краткое описание"),
                ),
                (
                    "requirements",
                    models.TextField(verbose_name="Условия и обязанности"),
                ),
                (
                    "schedule",
                    models.CharField(max_length=255, verbose_name="График работы"),
                ),
                (
                    "salary_type",
                    models.CharField(
                        choices=[("fixed", "Фиксированная"), ("percent", "Сдельная")],
                        default="fixed",
                        max_length=20,
                        verbose_name="Тип зарплаты",
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full", "Полная занятость"),
                            ("part", "Неполная занятость"),
                            ("flex", "Свободный график"),
                        ],
                        default="full",
                        max_length=20,
                        verbose_name="Тип занятости",
                    ),
                ),
                ("salary", models.CharField(max_length=255, verbose_name="Зарплата")),
                (
                    "image",
                    models.ImageField(
                        upload_to="vacancies/", verbose_name="Изображение"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
                "ordering": ["-created_at"],
            },
        ),
    ]
