# Generated by Django 6.0.5 on 2026-05-22 18:32

import apps.admin_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_vacancy_created_at_alter_vacancy_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(upload_to='vacancies/', validators=[apps.admin_utils.validate_image], verbose_name='Изображение'),
        ),
    ]
