# Generated by Django 6.0.5 on 2026-05-22 18:32

import apps.admin_utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_alter_category_options_category_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="categories/",
                validators=[apps.admin_utils.validate_image],
                verbose_name="Изображение",
            ),
        ),
    ]
