# Generated by Django 6.0.5 on 2026-05-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companygalleryimage',
            options={'ordering': ['order'], 'verbose_name': 'Фото галереи', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterField(
            model_name='companyfeature',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='companyfeature',
            name='icon',
            field=models.CharField(blank=True, help_text='Название Material Icon', max_length=100, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='companyfeature',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='companyfeature',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='companyfeature',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='companygalleryimage',
            name='image',
            field=models.ImageField(upload_to='company/gallery/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='companygalleryimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='companygalleryimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='companygalleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='telegram_url',
            field=models.URLField(blank=True, verbose_name='Ссылка Telegram'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='whatsapp_url',
            field=models.URLField(blank=True, verbose_name='Ссылка WhatsApp'),
        ),
        migrations.AlterField(
            model_name='companysection',
            name='image',
            field=models.ImageField(upload_to='company/sections/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='companysection',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='companysection',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='companysection',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='companysection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
