# Generated by Django 6.0.5 on 2026-06-02 16:14

import apps.admin_utils
import apps.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_alter_companygalleryimage_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="hero/slides/",
                        validators=[apps.admin_utils.validate_image],
                        verbose_name="Изображение слайда",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заголовок"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, verbose_name="Текст"),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True,
                        default="Подробнее",
                        max_length=100,
                        verbose_name="Текст кнопки",
                    ),
                ),
                (
                    "button_url",
                    models.CharField(
                        blank=True,
                        default="/products/",
                        max_length=500,
                        verbose_name="Ссылка кнопки",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Слайд карусели",
                "verbose_name_plural": "Слайды карусели",
                "ordering": ["sort_order"],
            },
            bases=(apps.mixins.ImageURLMixin, models.Model),
        ),
    ]
