# Generated by Django 6.0.5 on 2026-06-02 18:16

import apps.admin_utils
import apps.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0004_heroslide"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "straight_title",
                    models.CharField(
                        blank=True,
                        default="Brauni для бизнеса",
                        max_length=200,
                        verbose_name="Заголовок (прямая спираль)",
                    ),
                ),
                (
                    "straight_description",
                    models.TextField(
                        blank=True,
                        default="Готовый ассортимент для витрин и кофеен. Собираем стабильную линейку десертов, сэндвичей и гастрономии под ежедневные продажи.",
                        max_length=500,
                        verbose_name="Описание (прямая спираль)",
                    ),
                ),
                (
                    "straight_button_text",
                    models.CharField(
                        blank=True,
                        default="Смотреть каталог",
                        max_length=100,
                        verbose_name="Текст кнопки (прямая спираль)",
                    ),
                ),
                (
                    "straight_button_url",
                    models.CharField(
                        blank=True,
                        default="/products/",
                        max_length=500,
                        verbose_name="Ссылка кнопки (прямая спираль)",
                    ),
                ),
                (
                    "straight_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="home/blocks/",
                        validators=[apps.admin_utils.validate_image],
                        verbose_name="Изображение (прямая спираль)",
                    ),
                ),
                (
                    "curve_title",
                    models.CharField(
                        blank=True,
                        default="Работа в Brauni",
                        max_length=200,
                        verbose_name="Заголовок (изогнутая спираль)",
                    ),
                ),
                (
                    "curve_description",
                    models.TextField(
                        blank=True,
                        default="Собираем аккуратную команду для производства, кухни и ежедневной работы с продуктом.",
                        max_length=500,
                        verbose_name="Описание (изогнутая спираль)",
                    ),
                ),
                (
                    "curve_button_text",
                    models.CharField(
                        blank=True,
                        default="Смотреть вакансии",
                        max_length=100,
                        verbose_name="Текст кнопки (изогнутая спираль)",
                    ),
                ),
                (
                    "curve_button_url",
                    models.CharField(
                        blank=True,
                        default="/vacancies/",
                        max_length=500,
                        verbose_name="Ссылка кнопки (изогнутая спираль)",
                    ),
                ),
                (
                    "curve_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="home/blocks/",
                        validators=[apps.admin_utils.validate_image],
                        verbose_name="Изображение (изогнутая спираль)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Блоки главной страницы",
                "verbose_name_plural": "Блоки главной страницы",
            },
            bases=(apps.mixins.ImageURLMixin, models.Model),
        ),
    ]
