# Generated by Django 6.0.5 on 2026-06-06 17:08

import apps.admin_utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0005_homeblock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinfo",
            name="about_text",
            field=models.TextField(blank=True, verbose_name="Текст о компании"),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="company/hero/",
                verbose_name="Главное изображение",
            ),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="short_description",
            field=models.TextField(blank=True, verbose_name="Краткое описание"),
        ),
        migrations.AlterField(
            model_name="companysection",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="company/sections/",
                validators=[apps.admin_utils.validate_image],
                verbose_name="Изображение",
            ),
        ),
    ]
