# Generated by Django 6.0.5 on 2026-06-07 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0003_alter_category_image"),
        ("company", "0006_alter_companyinfo_about_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="heroslide",
            name="link_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Если выбрана категория — кнопка будет вести на её страницу.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.category",
                verbose_name="Категория для перехода",
            ),
        ),
    ]
