# Generated by Django 6.0.5 on 2026-06-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_add_hero_slide_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='bank_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Наименование банка'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='bik',
            field=models.CharField(blank=True, max_length=32, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='correspondent_account',
            field=models.CharField(blank=True, max_length=50, verbose_name='Корреспондентский счёт'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='director_name',
            field=models.CharField(blank=True, help_text='Например: Иванов Иван Иванович', max_length=255, verbose_name='ФИО руководителя'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='director_position',
            field=models.CharField(blank=True, default='Генеральный директор', max_length=255, verbose_name='Должность руководителя'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='kpp',
            field=models.CharField(blank=True, max_length=32, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='legal_address',
            field=models.TextField(blank=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Например: ООО «Брауни Фуд»', max_length=500, verbose_name='Полное юридическое наименование'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='payment_account',
            field=models.CharField(blank=True, max_length=50, verbose_name='Расчётный счёт'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='address',
            field=models.TextField(blank=True, verbose_name='Фактический адрес'),
        ),
    ]
